#!/bin/bash

# For the purpose of the developer assessment, the script will create the DynamoDB tables locally
# AWS cli is required to run this script (I could use Node or Python, but I wanted to keep it simple)

# Check if the user has aws cli installed
if ! [ -x "$(command -v aws)" ]; then
  echo 'Error: aws cli is not installed.' >&2
  exit 1
fi

# Create the tables
echo "Setting up DynamoDB tables..."

# Inventory Table
# The primary key will be the id of the item, generated by the application using uuid v4()
# In the context of NoSQL, the remainder attributes will not be defined in the table schema
# but they will be defined as interfaces in the application and validated there
# The items here are the bare minimum for the purpose of the assessment
# In production, the table should be have autoscaling enabled

output=$(aws dynamodb create-table \
  --table-name Inventory \
  --attribute-definitions \
    AttributeName=id,AttributeType=S \
  --key-schema \
    AttributeName=id,KeyType=HASH \
  --provisioned-throughput \
    ReadCapacityUnits=3,WriteCapacityUnits=3 \
  --endpoint-url http://localhost:8000 2>&1)

# Check if the table was created
if echo "$output" | grep -q "ResourceNotFoundException"; then
  echo "Error: Table Inventory was not created."
elif echo "$output" | grep -q "ResourceInUseException"; then
  echo "Table Inventory already exists."
else
  echo "Table Inventory created."
fi

# Done creating tables
echo "DynamoDB tables setup complete."